### ISSUE TITLE
PHP_HOST missing prevents nginx starting

### ISSUE THREAD

**Issue by crayfishuk** [fauzie/docker-whmcs#2]
Starting using docker-compose-local.yml fails to work with the error
`
invalid number of arguments in "fastcgi_param" directive in /etc/nginx/conf.d/default.conf:44
`
Searching the `/root/app/default_vhosts` https://github.com/fauzie/docker-whmcs/blob/7838b11e9bd5c60c84257a5fd9c3c389099fe1e9/root/app/default-vhost.tmpl#L44 seems to refer to PHP_HOST which isn't part of the required build environment, and defaults to whmcs.local, which doesn't exist either...

Defined `PHP_VHOST` in my `whmcs:environment:` and it starts -- but something is missing from the default build?

**Comment by JavierAgueroCL** [comment]
I got the same error.

`invalid number of arguments in "fastcgi_param" directive in /etc/nginx/conf.d/default.conf:44`

**Comment by crossworth** [comment]
I'm facing the same problem.

What happens is that during the Dockerfile build the `PHP_VHOST` variable is set to `DOCKER_HOST`, which is only set when using `docker-machine`.

https://github.com/fauzie/docker-whmcs/blob/master/Dockerfile#L7

I override it on docker-composer:
```
environment:
      WORKER_PROCESSES: 4
      VIRTUAL_HOST: whmcs.test
      PHP_VHOST: whmcs.test
      APP_PASSWORD: userapppassword
      WHMCS_SERVER_IP: 172.18.18.1
      HTTPS: "on"
```

I'm not sure whats the best way to resolve this issue.

Maybe setting the `SERVER_NAME` to `_` to catch all since it's a docker container after all.

>  In catch-all server examples the strange name “_” can be seen:

    server {
        listen       80  default_server;
        server_name  _;
        return       444;
    }

[Ref](https://nginx.org/en/docs/http/server_names.html)
